### PR TITLE
Upgrade React Native to 0.26

### LINKED ISSUE #1026: React Native upgrade to 0.26
Attempting [upgrading steps in our wiki](https://github.com/DoSomething/LetsDoThis-iOS/wiki/Development#upgrading-react-native) are throwing errors.

Running `npm install --save react-native@0.26` [throws this warning](https://github.com/facebook/react-native/issues/7697):
> react-native@0.26.1 requires a peer of react@15.0.2 but none was installed.

Running the build leads to a RSOD with some steps for troubleshooting, referencing https://github.com/facebook/react-native/issues/4968

Running `npm install --save react@15.0.2` after the warning about no React installed results in new RSOD. This [SO thread](http://stackoverflow.com/a/37053008/1470725) mentions that importing React from React Native will stop working in 0.26 (was deprecated in 0.25.1). 

> 2016-05-23 11:18:19.868 [error][tid:com.facebook.react.JavaScript] _reactNative2.default.createClass is not a function. (In '_reactNative2.default.createClass', '_reactNative2.default.createClass' is undefined)
2016-05-23 11:18:19.870 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: _reactNative2.default.createClass is not a function. (In '_reactNative2.default.createClass', '_reactNative2.default.createClass' is undefined)
May 23 11:18:21  DoSomething[4139] <Notice>: starting profile request using - 3.1-77 with options: 1fc7e
2016-05-23 11:18:21.886 DoSomething[4139:64906] Tapjoy connect succeeded
2016-05-23 11:18:21.892 DoSomething[4139:64906] __68-[DSOUserManager continueSessionWithCompletionHandler:errorHandler:]_block_invoke line 132 $ user 55e8daf5a59dbfa8118b4755
2016-05-23 11:18:21.892 DoSomething[4139:64906] -[GAI(LDT) trackScreenView:] line 19 $ news
2016-05-23 11:18:21.923 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module.
May 23 11:18:21  DoSomething[4139] <Error>: Module AppRegistry is not a registered callable module.
2016-05-23 11:18:21.924 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module.
May 23 11:18:21  DoSomething[4139] <Critical>: Unhandled JS Exception: Module AppRegistry is not a registered callable module.
2016-05-23 11:18:22.892 DoSomething[4139:64906] -canOpenURL: failed for URL: "about:blank" - error: "This app is not allowed to query for scheme about"

### PR DESCRIPTION
**Pull request by aaronschachter**
Closes #1026. They're not kidding about those breaking changes!

Starting [0.26](https://github.com/facebook/react-native/releases/tag/v0.26.0): 
> React API must be now required from `react` package

### CODE REVIEW

**Comment by aaronschachter** [comment]
[Fixes](https://github.com/DoSomething/LetsDoThis-iOS/pull/1027/commits/6c8d1069cac535e843b86ef636bfce2d8b127930) https://github.com/DoSomething/LetsDoThis-iOS/issues/1026#issuecomment-221123773 thanks to  https://github.com/facebook/react-native/issues/7697#issuecomment-221126318

@lkpttn To run the build, you'll need to update your local setup via `npm update && pod install`

File: ReactComponents/CauseListView.js [hunk 1]
```diff
@@ -1,10 +1,11 @@
 'use strict';
 
-import React, {
+import React, {Component} from 'react';
+
+import {
   AppRegistry,
   ActivityIndicatorIOS,
   ListView,
-  Component,
```
Comment (aaronschachter) [inline ReactComponents/CauseListView.js]: Not certain yet but I suspect we don't need this `Component` at all...

File: ReactComponents/NetworkImage.js [hunk 2]
```diff
@@ -1,6 +1,8 @@
 'use strict';
 
-import React, {
+import React from 'react';
+
+import {
   Component,
```
Comment (aaronschachter) [inline ReactComponents/NetworkImage.js]: Moved this into React, but thinking we actually don't need (refs https://github.com/DoSomething/LetsDoThis-iOS/pull/1027/files#r64401642)

**Comment by aaronschachter** [comment]
Testing `UserView` and get a new warning for Profiles with an empty section:
> May 24 08:22:17  DoSomething[3496] <Warning>: Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.
